source ~/.vimrc

tnoremap <C-[> <C-\><C-n>
nnoremap <leader>c :terminal<CR>

" movement from terminal
tnoremap <C-j> <C-\><C-n><C-w>j
tnoremap <C-k> <C-\><C-n><C-w>k
tnoremap <C-h> <C-\><C-n><C-w>h
tnoremap <C-l> <C-\><C-n><C-w>l

" On terminal panel enter, start instert
autocmd BufWinEnter,WinEnter term://* startinsert
